#!/bin/bash
# Test example for Silent Restriction Site Finder
# Uses a simple test gene encoding: MKTII...

echo "Testing Silent Restriction Site Finder"
echo "========================================"
echo ""

# Simple test case: short gene
DNA="ATGAAGACAATCATCGGTGCTGGTGCTAAGTTCGAATTCGGATCCTAG"
PROTEIN="MKTIIGGAKFE"

echo "Test 1: Short gene (MKTIIGGAKFE)"
echo "DNA: $DNA"
echo "Protein: $PROTEIN"
echo ""

python silent_sites.py \
    --dna "$DNA" \
    --protein "$PROTEIN" \
    --mutations 2 \
    --min-length 4

echo ""
echo "========================================"
echo ""

# Test 2: Show all mutations (including non-silent)
echo "Test 2: Same gene, showing all mutations"
python silent_sites.py \
    --dna "$DNA" \
    --protein "$PROTEIN" \
    --mutations 2 \
    --min-length 4 \
    --show-all

echo ""
echo "========================================"
echo ""

# Test 3: Longer sequence with more options
DNA_LONG="ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA"
PROTEIN_LONG="MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK"

echo "Test 3: GFP gene (partial, 238 aa)"
echo "Finding sites with exactly 0 mutations (already present)"
python silent_sites.py \
    --dna "$DNA_LONG" \
    --protein "$PROTEIN_LONG" \
    --mutations 0 \
    --min-length 6

echo ""
echo "========================================"
echo "All tests complete!"
