#!/usr/bin/env python3
"""
Build AVD059-AVD099 intron-retention cassette plasmids.

Each construct inserts a splice donor/acceptor pair (from HEK293 retained introns)
flanking GT/AG-depleted GGGGS5-VHH3-GGGGS1 at VR4 of AVD002.

Two mRNA products per construct:
  Spliced  → near-WT VP: ...GSG-[6aa scar]-QNQQTLKF...  (18 bp insertion)
  Retained → VHH display: ...GSG-[164aa full]-QNQQTLKF... (492 bp insertion)

Base plasmid: AVD002-Rep2Mut2Cap9-6R-wt-5fold (7104 bp)
Insertion point: bp 3743 (VR4, after SKTIN**GSG**, before **QNQQTLKF**)

Source: design_linker_Sequences_6mer.xlsx (560 donor/acceptor pairs)
Filter: Predicted_log2FC loop4 >= 1.0 AND contains_stop_codon == False → 41 constructs
"""

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.SeqFeature import SeqFeature, FeatureLocation, CompoundLocation
from datetime import datetime
from pathlib import Path
import csv
import sys
import openpyxl

# ─── Project paths ───────────────────────────────────────────────────────────
PROJECT_DIR = Path(__file__).parent.parent
CONSTRUCTS_DIR = PROJECT_DIR.parent / "dna_engineer_agent" / "constructs"
SCRIPTS_DIR = PROJECT_DIR / "scripts"
ROOT_DIR = PROJECT_DIR.parent / "dna_engineer_agent"

# ─── Constants ───────────────────────────────────────────────────────────────
INSERTION_POINT = 3743        # bp position in AVD002 (0-indexed)
VP1_START = 2378              # VP1 CDS start (0-indexed)
AAP_END = 3498                # AAP CDS end (0-indexed, exclusive)

# Amino acid sequences
VHH3_AA = ("EVQLVESGGGLVQPGGSLRLSCAASGFTFSTADMGWFRQAPGKGRELVAAVSGSGFSTYSD"
           "SVEGRFTISRDNAKRMVYLQMNSLRAEDTAVYYCAKATISLYYAMDVWGQGTTVTVSS")
GGGGS5_AA = "GGGGSGGGGSGGGGSGGGGSGGGGS"
GGGGS1_AA = "GGGGS"

# ─── GT/AG-depleted codon-optimized sequences ───────────────────────────────
# GGGGS5: Manually designed with varied GGC/GGG codons + TCC/TCG/TCT Ser.
# Zero GT, zero AG dinucleotides. Max G-run = 5.
GGGGS5_OPT = (
    "GGCGGCGGCGGCTCG"   # Rep1: GGC GGC GGC GGC TCG
    "GGCGGCGGGGGCTCC"   # Rep2: GGC GGC GGG GGC TCC
    "GGCGGGGGCGGCTCC"   # Rep3: GGC GGG GGC GGC TCC
    "GGGGGCGGCGGCTCT"   # Rep4: GGG GGC GGC GGC TCT
    "GGGGGCGGGGGCTCT"   # Rep5: GGG GGC GGG GGC TCT
)

# VHH3: v2 optimized — GT/AG-depleted + context-optimized to minimize cryptic
#        splice scores (MaxEntScan, U1 dG). 12 GT, 7 AG (all locked junctions).
#        Generated by optimize_intron_body_codons.py.
VHH3_OPT = (
    "GAAGTCCAACTCGTCGAATCCGGCGGCGGCCTCGTCCAACCCGGCGGCTCTCTGCGGCTT"
    "TCATGCGCCGCCTCTGGATTCACATTTTCCACCGCCGATATGGGATGGTTCCGGCAAGCC"
    "CCCGGCAAAGGCCGGGAACTCGTCGCCGCCGTTTCCGGCTCTGGATTCTCTACATATTCC"
    "GATTCCGTCGAAGGCCGATTCACCATCTCTCGGGATAATGCCAAACGCATGGTCTACCTG"
    "CAAATGAATTCCCTGCGGGCCGAAGATACCGCCGTCTACTATTGCGCCAAAGCCACCATT"
    "TCCTTATATTATGCCATGGACGTCTGGGGCCAAGGCACCACCGTCACCGTTTCCTCC"
)

# GGGGS1: GT/AG-free, same design principles.
GGGGS1_OPT = "GGCGGCGGGGGCTCG"

# Intron body = GGGGS5 + VHH3 + GGGGS1 = 75 + 357 + 15 = 447 bp
INTRON_BODY = GGGGS5_OPT + VHH3_OPT + GGGGS1_OPT

# ─── Restriction site checking ──────────────────────────────────────────────
FORBIDDEN_SITES = {
    "BsaI": "GGTCTC",
    "BsmBI": "CGTCTC",
    "BamHI": "GGATCC",
}


def reverse_complement(seq):
    """Return reverse complement of a DNA sequence."""
    comp = str.maketrans("ACGTacgt", "TGCAtgca")
    return seq.translate(comp)[::-1]


def count_site_dsdna(sequence, site):
    """Count occurrences of a restriction site on both strands (BUG-003)."""
    rc_site = reverse_complement(site)
    fwd = sequence.upper().count(site.upper())
    if site.upper() == rc_site.upper():  # palindromic
        return fwd
    return fwd + sequence.upper().count(rc_site.upper())


def check_forbidden_sites(sequence, label=""):
    """Check for forbidden restriction sites on both strands."""
    issues = []
    for name, site in FORBIDDEN_SITES.items():
        count = count_site_dsdna(sequence, site)
        if count > 0:
            issues.append(f"{name} ({site}) found {count}x in {label}")
    return issues


# ─── Feature shifting ───────────────────────────────────────────────────────

def shift_feature_location(location, insertion_point, shift_amount):
    """Shift a feature location if it's after the insertion point."""
    if isinstance(location, CompoundLocation):
        new_parts = []
        for part in location.parts:
            new_parts.append(
                shift_feature_location(part, insertion_point, shift_amount)
            )
        return CompoundLocation(new_parts, operator=location.operator)

    start = location.start
    end = location.end
    strand = location.strand

    if start >= insertion_point:
        start += shift_amount
        end += shift_amount
    elif start < insertion_point < end:
        end += shift_amount

    return FeatureLocation(start, end, strand=strand)


# ─── Excel parsing ──────────────────────────────────────────────────────────

def parse_and_filter_excel(excel_path):
    """Parse 560 donor/acceptor pairs and filter to constructs with
    Predicted_log2FC loop4 >= 1.0 and contains_stop_codon == False.
    """
    wb = openpyxl.load_workbook(str(excel_path))
    ws = wb.active
    headers = [cell.value for cell in ws[1]]

    # Column indices
    cols = {h: i for i, h in enumerate(headers)}
    required = [
        "donor", "acceptor", "Predicted_log2FC loop4",
        "contains_stop_codon", "geneSymbol", "splicing_scar_AA",
        "donor_spliced_DNA", "acceptor_spliced_DNA",
    ]
    for r in required:
        if r not in cols:
            raise KeyError(f"Missing column '{r}' in Excel. Available: {list(cols.keys())}")

    passing = []
    for row_idx in range(2, ws.max_row + 1):
        row = [cell.value for cell in ws[row_idx]]
        log2fc = row[cols["Predicted_log2FC loop4"]]
        stop = row[cols["contains_stop_codon"]]

        if log2fc is None or log2fc < 1.0:
            continue
        if stop is True or stop == "True":
            continue

        passing.append({
            "donor": row[cols["donor"]],
            "acceptor": row[cols["acceptor"]],
            "log2fc": log2fc,
            "gene_symbol": row[cols["geneSymbol"]],
            "scar_aa": row[cols["splicing_scar_AA"]],
            "donor_spliced": row[cols["donor_spliced_DNA"]],
            "acceptor_spliced": row[cols["acceptor_spliced_DNA"]],
        })

    # Sort by log2FC descending
    passing.sort(key=lambda x: -x["log2fc"])
    return passing


# ─── Insert building ────────────────────────────────────────────────────────

def check_junction_gt_ag(left_seq, right_seq, label):
    """Check for GT/AG at the single-nucleotide boundary between two sequences."""
    boundary = left_seq[-1] + right_seq[0]
    issues = []
    if "GT" in boundary:
        issues.append(f"GT at {label} boundary: ...{left_seq[-3:]}|{right_seq[:3]}...")
    if "AG" in boundary:
        issues.append(f"AG at {label} boundary: ...{left_seq[-3:]}|{right_seq[:3]}...")
    return issues


def build_insert(donor_15bp, acceptor_30bp):
    """Build the 492 bp intron-retention cassette.

    Architecture:
      donor(15bp) + GGGGS5(75bp) + VHH3(357bp) + GGGGS1(15bp) + acceptor(30bp)

    Returns (insert_dna, warnings) where warnings is a list of strings.
    """
    donor = donor_15bp.upper()
    acceptor = acceptor_30bp.upper()

    assert len(donor) == 15, f"Donor must be 15 bp, got {len(donor)}"
    assert len(acceptor) == 30, f"Acceptor must be 30 bp, got {len(acceptor)}"

    insert = donor + INTRON_BODY + acceptor
    assert len(insert) == 492, f"Insert must be 492 bp, got {len(insert)}"

    warnings = []

    # Check junction GT/AG at donor_intronic → GGGGS5 boundary
    donor_intronic = donor[9:]   # 6 bp intronic portion
    warnings.extend(
        check_junction_gt_ag(donor_intronic, GGGGS5_OPT, "donor→GGGGS5")
    )

    # Check junction GT/AG at GGGGS1 → acceptor_intronic boundary
    acceptor_intronic = acceptor[:19]  # 19 bp intronic portion
    warnings.extend(
        check_junction_gt_ag(GGGGS1_OPT, acceptor_intronic, "GGGGS1→acceptor")
    )

    return insert, warnings


def verify_retained_product(insert_492bp, gene_symbol):
    """Translate the full 492 bp retained insert and check for stops.

    The insert must be in-frame with VP1 (verified by the caller).
    Returns (aa_seq, has_stop, stop_positions).
    """
    aa_seq = str(Seq(insert_492bp).translate())
    stop_positions = [i for i, c in enumerate(aa_seq) if c == "*"]
    return aa_seq, len(stop_positions) > 0, stop_positions


def verify_spliced_scar(donor_15bp, acceptor_30bp, expected_scar_aa):
    """Verify the spliced product (6-aa scar) matches expected."""
    donor_exonic = donor_15bp[:9]
    acceptor_exonic = acceptor_30bp[21:]  # last 9 bp after AG
    scar_dna = donor_exonic + acceptor_exonic
    assert len(scar_dna) == 18, f"Scar must be 18 bp, got {len(scar_dna)}"
    scar_aa = str(Seq(scar_dna).translate())
    if scar_aa != expected_scar_aa:
        return False, scar_aa, scar_dna
    return True, scar_aa, scar_dna


# ─── AVD002 loading ─────────────────────────────────────────────────────────

def load_avd002():
    """Load AVD002 base plasmid from GenBank file."""
    gb_path = CONSTRUCTS_DIR / "AVD002-Rep2Mut2Cap9-6R-wt-5fold.gb"
    if not gb_path.exists():
        # Try .dna format
        dna_path = CONSTRUCTS_DIR / "AVD002-Rep2Mut2Cap9-6R-wt.dna"
        if dna_path.exists():
            record = SeqIO.read(str(dna_path), "snapgene")
        else:
            raise FileNotFoundError(
                f"AVD002 not found at {gb_path} or {dna_path}"
            )
    else:
        record = SeqIO.read(str(gb_path), "genbank")

    seq = str(record.seq).upper()
    assert len(seq) == 7104, f"AVD002 should be 7104 bp, got {len(seq)}"

    # Verify critical positions
    assert seq[2378:2381] == "ATG", f"VP1 start: {seq[2378:2381]}"
    assert seq[2789:2792] == "ACG", f"VP2 start: {seq[2789:2792]}"
    assert seq[2984:2987] == "ATG", f"VP3 start: {seq[2984:2987]}"

    # Verify insertion site flanking sequences
    # Upstream: SKTINGSG (aa 448-455 of VP1)
    upstream_dna = seq[3719:3743]  # 8 codons = 24 bp
    upstream_aa = str(Seq(upstream_dna).translate())
    assert upstream_aa.endswith("GSG"), (
        f"Upstream should end with GSG, got {upstream_aa}"
    )

    # Downstream: QNQQTLKF (aa 456-463 of VP1)
    downstream_dna = seq[3743:3767]  # 8 codons = 24 bp
    downstream_aa = str(Seq(downstream_dna).translate())
    assert downstream_aa.startswith("QNQQTLKF"), (
        f"Downstream should start with QNQQTLKF, got {downstream_aa}"
    )

    # Verify frame offset: insertion must be at codon boundary
    frame_offset = (INSERTION_POINT - VP1_START) % 3
    assert frame_offset == 0, (
        f"Frame offset at insertion should be 0 (codon boundary), got {frame_offset}"
    )

    print(f"  Loaded AVD002: {len(seq)} bp, {len(record.features)} features")
    print(f"  VP1 start (bp 2379): {seq[2378:2381]}")
    print(f"  Insertion at bp {INSERTION_POINT}: ...{upstream_aa[-3:]}|{downstream_aa[:8]}...")
    print(f"  Frame offset: ({INSERTION_POINT} - {VP1_START}) mod 3 = {frame_offset}")
    return record


# ─── Construct building ─────────────────────────────────────────────────────

def build_construct(avd002_record, donor_15bp, acceptor_30bp, avd_id,
                    gene_symbol, scar_aa, log2fc):
    """Build one intron-retention construct from AVD002."""
    avd002_seq = str(avd002_record.seq).upper()

    # Build insert
    insert_dna, junction_warnings = build_insert(donor_15bp, acceptor_30bp)

    # Verify retained product (no stops in 164 aa)
    retained_aa, has_stop, stop_positions = verify_retained_product(
        insert_dna, gene_symbol
    )

    # Verify spliced scar
    scar_ok, actual_scar_aa, scar_dna = verify_spliced_scar(
        donor_15bp, acceptor_30bp, scar_aa
    )

    # Build final plasmid
    new_seq = avd002_seq[:INSERTION_POINT] + insert_dna + avd002_seq[INSERTION_POINT:]
    insert_len = len(insert_dna)
    expected_size = 7104 + insert_len
    assert len(new_seq) == expected_size, (
        f"{avd_id}: expected {expected_size} bp, got {len(new_seq)}"
    )

    # Check restriction sites in insert (both strands, BUG-003)
    site_issues = check_forbidden_sites(insert_dna, f"{avd_id} insert")
    # Also check full plasmid for new sites
    for name, site in FORBIDDEN_SITES.items():
        orig_count = count_site_dsdna(avd002_seq, site)
        new_count = count_site_dsdna(new_seq, site)
        if new_count > orig_count:
            site_issues.append(
                f"{name} increased from {orig_count} to {new_count} in full plasmid"
            )

    # Verify flanking sequences in final construct
    upstream_aa = str(Seq(new_seq[3719:INSERTION_POINT]).translate())
    downstream_aa = str(
        Seq(new_seq[INSERTION_POINT + insert_len:
                     INSERTION_POINT + insert_len + 24]).translate()
    )

    # Build SeqRecord
    record = SeqRecord(
        Seq(new_seq),
        id=avd_id,
        name=avd_id,
        description=(
            f"Rep2Mut2Cap9-VR4-IntronRetention-{gene_symbol} | "
            f"Scar={actual_scar_aa} log2FC={log2fc:.3f}"
        ),
        annotations={
            "molecule_type": "DNA",
            "topology": "circular",
            "date": datetime.now().strftime("%d-%b-%Y").upper(),
        },
    )

    # Copy and shift features
    features = []
    for feat in avd002_record.features:
        new_location = shift_feature_location(
            feat.location, INSERTION_POINT, insert_len
        )
        new_feat = SeqFeature(
            location=new_location,
            type=feat.type,
            qualifiers=dict(feat.qualifiers),
        )

        label = feat.qualifiers.get("label", [""])[0]
        if label == "VP1":
            new_feat.qualifiers["label"] = ["VP1-IntronRetention"]
            new_feat.qualifiers["note"] = [
                f"AAV9 VP1 with intron-retention cassette at VR-IV. "
                f"Splice donor/acceptor from {gene_symbol}."
            ]

        features.append(new_feat)

    # Add cassette annotations
    pos = INSERTION_POINT

    # Donor exonic (9 bp)
    features.append(SeqFeature(
        FeatureLocation(pos, pos + 9),
        type="misc_feature",
        qualifiers={
            "label": [f"donor_exonic_{gene_symbol}"],
            "note": [f"Splice donor exonic (9 bp) from {gene_symbol}"],
        },
    ))

    # Splice donor site (GT dinucleotide)
    donor_site_label = "GT" if donor_15bp[9:11].upper() == "GT" else donor_15bp[9:11].upper()
    features.append(SeqFeature(
        FeatureLocation(pos + 9, pos + 11),
        type="misc_feature",
        qualifiers={
            "label": [f"splice_donor_{donor_site_label}"],
            "note": [f"5' splice site ({donor_site_label})"],
        },
    ))

    # Donor intronic (4 bp after GT)
    features.append(SeqFeature(
        FeatureLocation(pos + 11, pos + 15),
        type="misc_feature",
        qualifiers={
            "label": ["donor_intronic"],
            "note": ["Donor intronic sequence (4 bp)"],
        },
    ))

    # GGGGS5 linker
    features.append(SeqFeature(
        FeatureLocation(pos + 15, pos + 15 + 75),
        type="misc_feature",
        qualifiers={
            "label": ["GGGGS5_GTAGdepleted"],
            "note": ["(GGGGS)x5 linker, GT/AG-depleted codons (75 bp)"],
        },
    ))

    # VHH3
    features.append(SeqFeature(
        FeatureLocation(pos + 90, pos + 90 + 357, strand=+1),
        type="CDS",
        qualifiers={
            "label": ["VHH3_anti-ALPL"],
            "note": [f"Anti-ALPL VHH nanobody, {len(VHH3_AA)} aa, GT/AG-depleted"],
            "translation": [VHH3_AA],
        },
    ))

    # GGGGS1 linker
    features.append(SeqFeature(
        FeatureLocation(pos + 90 + 357, pos + 90 + 357 + 15),
        type="misc_feature",
        qualifiers={
            "label": ["GGGGS1_GTAGdepleted"],
            "note": ["(GGGGS)x1 linker, GT/AG-depleted codons (15 bp)"],
        },
    ))

    # Acceptor intronic (19 bp)
    features.append(SeqFeature(
        FeatureLocation(pos + 462, pos + 462 + 19),
        type="misc_feature",
        qualifiers={
            "label": ["acceptor_intronic"],
            "note": ["Acceptor intronic sequence (19 bp)"],
        },
    ))

    # Splice acceptor site (AG dinucleotide)
    features.append(SeqFeature(
        FeatureLocation(pos + 462 + 19, pos + 462 + 21),
        type="misc_feature",
        qualifiers={
            "label": ["splice_acceptor_AG"],
            "note": ["3' splice site (AG)"],
        },
    ))

    # Acceptor exonic (9 bp)
    features.append(SeqFeature(
        FeatureLocation(pos + 462 + 21, pos + 492),
        type="misc_feature",
        qualifiers={
            "label": [f"acceptor_exonic_{gene_symbol}"],
            "note": [f"Splice acceptor exonic (9 bp) from {gene_symbol}"],
        },
    ))

    # Full intron annotation (everything between donor GT and acceptor AG)
    features.append(SeqFeature(
        FeatureLocation(pos + 9, pos + 462 + 21),
        type="intron",
        qualifiers={
            "label": [f"intron_{gene_symbol}"],
            "note": [
                f"Synthetic intron from {gene_symbol} retained intron. "
                f"Contains GGGGS5-VHH3-GGGGS1 (GT/AG-depleted). "
                f"Expected retention ~10-20%."
            ],
        },
    ))

    record.features = features

    # Collect QC info
    qc = {
        "avd_id": avd_id,
        "gene_symbol": gene_symbol,
        "donor": donor_15bp,
        "acceptor": acceptor_30bp,
        "scar_aa": actual_scar_aa,
        "scar_dna": scar_dna,
        "log2fc": log2fc,
        "retained_has_stop": has_stop,
        "retained_stop_positions": stop_positions,
        "retained_aa": retained_aa,
        "insert_gt_count": insert_dna.count("GT"),
        "insert_ag_count": insert_dna.count("AG"),
        "junction_warnings": junction_warnings,
        "site_issues": site_issues,
        "scar_ok": scar_ok,
        "upstream_aa": upstream_aa,
        "downstream_aa": downstream_aa,
        "total_size": len(new_seq),
    }

    return record, qc


# ─── Export ──────────────────────────────────────────────────────────────────

def export_genbank(record, output_path):
    """Write GenBank file."""
    SeqIO.write(record, str(output_path), "genbank")


def export_summary_csv(qc_list, output_path):
    """Write summary CSV with all construct QC data."""
    fieldnames = [
        "avd_id", "gene_symbol", "log2fc", "scar_aa", "scar_dna",
        "total_size", "retained_has_stop", "retained_stop_positions",
        "insert_gt_count", "insert_ag_count",
        "junction_warnings", "site_issues", "scar_ok",
        "upstream_aa", "downstream_aa",
        "donor", "acceptor",
    ]
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for qc in qc_list:
            row = dict(qc)
            row["retained_stop_positions"] = ";".join(
                str(p) for p in qc["retained_stop_positions"]
            )
            row["junction_warnings"] = "; ".join(qc["junction_warnings"])
            row["site_issues"] = "; ".join(qc["site_issues"])
            writer.writerow(row)


# ─── Verification ───────────────────────────────────────────────────────────

def verify_optimized_sequences():
    """Verify the GT/AG-depleted sequences before building constructs."""
    print("Verifying optimized intron body sequences...")

    # Translation checks
    assert str(Seq(GGGGS5_OPT).translate()) == GGGGS5_AA, "GGGGS5 translation mismatch"
    assert str(Seq(VHH3_OPT).translate()) == VHH3_AA, "VHH3 translation mismatch"
    assert str(Seq(GGGGS1_OPT).translate()) == GGGGS1_AA, "GGGGS1 translation mismatch"
    assert len(INTRON_BODY) == 447, f"Intron body should be 447 bp, got {len(INTRON_BODY)}"

    # GT/AG counts
    print(f"  GGGGS5: {len(GGGGS5_OPT)} bp, GT={GGGGS5_OPT.count('GT')}, AG={GGGGS5_OPT.count('AG')}")
    print(f"  VHH3:   {len(VHH3_OPT)} bp, GT={VHH3_OPT.count('GT')}, AG={VHH3_OPT.count('AG')}")
    print(f"  GGGGS1: {len(GGGGS1_OPT)} bp, GT={GGGGS1_OPT.count('GT')}, AG={GGGGS1_OPT.count('AG')}")
    print(f"  Total:  {len(INTRON_BODY)} bp, GT={INTRON_BODY.count('GT')}, AG={INTRON_BODY.count('AG')}")

    # Restriction site checks (both strands)
    issues = check_forbidden_sites(INTRON_BODY, "intron body")
    if issues:
        for issue in issues:
            print(f"  WARNING: {issue}")
    else:
        print("  No forbidden restriction sites in intron body")

    print("  Optimized sequences verified OK")


# ─── Main pipeline ──────────────────────────────────────────────────────────

def main():
    print("=" * 72)
    print("Building AVD059-AVD099 Intron-Retention Cassette Plasmids")
    print("=" * 72)

    # Step 0: Verify optimized sequences
    verify_optimized_sequences()

    # Step 1: Load AVD002
    print("\nLoading AVD002 base plasmid...")
    avd002 = load_avd002()

    # Step 2: Parse and filter Excel
    excel_path = ROOT_DIR / "design_linker_Sequences_6mer.xlsx"
    if not excel_path.exists():
        raise FileNotFoundError(f"Excel not found: {excel_path}")

    print(f"\nParsing {excel_path.name}...")
    constructs = parse_and_filter_excel(excel_path)
    print(f"  {len(constructs)} constructs pass filter (log2FC >= 1.0, no stop codon)")

    # Step 3: Build all constructs
    CONSTRUCTS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"\nBuilding {len(constructs)} constructs...")
    print("-" * 72)

    records = []
    qc_list = []
    skipped = []

    for idx, construct in enumerate(constructs):
        avd_id = f"AVD{59 + idx:03d}"
        gene = construct["gene_symbol"]
        donor = construct["donor"]
        acceptor = construct["acceptor"]
        scar_aa = construct["scar_aa"]
        log2fc = construct["log2fc"]

        print(f"\n  {avd_id} ({gene}, scar={scar_aa}, log2FC={log2fc:.3f}):")

        record, qc = build_construct(
            avd002, donor, acceptor, avd_id, gene, scar_aa, log2fc
        )

        # Check for critical issues
        critical = False

        if qc["retained_has_stop"]:
            print(f"    SKIP: Stop codon(s) in retained product at aa {qc['retained_stop_positions']}")
            skipped.append((avd_id, gene, "stop_in_retained", qc["retained_stop_positions"]))
            critical = True

        if qc["site_issues"]:
            for issue in qc["site_issues"]:
                print(f"    WARNING: {issue}")

        if not qc["scar_ok"]:
            print(f"    WARNING: Scar mismatch - expected {scar_aa}, got {qc['scar_aa']}")

        if qc["junction_warnings"]:
            for w in qc["junction_warnings"]:
                print(f"    note: {w}")

        if not critical:
            print(f"    OK: {qc['total_size']} bp, scar={qc['scar_aa']}, "
                  f"GT={qc['insert_gt_count']}, AG={qc['insert_ag_count']}")
            records.append(record)
            qc_list.append(qc)

    # Step 4: Export
    print("\n" + "=" * 72)
    print(f"Exporting {len(records)} constructs (skipped {len(skipped)})...")
    print("=" * 72)

    for record in records:
        avd_id = record.id
        gene = record.description.split("-")[-1].split(" |")[0]
        filename = f"{avd_id}-Rep2Mut2Cap9-VR4-IR-{gene}.gb"
        export_genbank(record, CONSTRUCTS_DIR / filename)
        print(f"  Wrote {filename}")

    # Summary CSV
    csv_path = CONSTRUCTS_DIR / "AVD059-099_intron_retention_summary.csv"
    export_summary_csv(qc_list, csv_path)
    print(f"  Wrote {csv_path.name}")

    # Final report
    print("\n" + "=" * 72)
    print("BUILD SUMMARY")
    print("=" * 72)
    print(f"  Constructs built: {len(records)}")
    print(f"  Constructs skipped: {len(skipped)}")
    if skipped:
        for avd_id, gene, reason, detail in skipped:
            print(f"    - {avd_id} ({gene}): {reason} {detail}")
    print(f"  Output directory: {CONSTRUCTS_DIR}")
    print(f"  AVD range: AVD059-AVD{59 + len(constructs) - 1:03d}")

    # Print summary table
    print(f"\n{'AVD ID':<10} {'Gene':<12} {'Scar':<8} {'log2FC':>8} "
          f"{'Size':>6} {'GT':>4} {'AG':>4} {'Stops':>6}")
    print("-" * 68)
    for qc in qc_list:
        stops = "NONE" if not qc["retained_has_stop"] else f"aa {qc['retained_stop_positions']}"
        print(f"{qc['avd_id']:<10} {qc['gene_symbol']:<12} {qc['scar_aa']:<8} "
              f"{qc['log2fc']:>8.3f} {qc['total_size']:>6} "
              f"{qc['insert_gt_count']:>4} {qc['insert_ag_count']:>4} {stops:>6}")

    print(f"\nDone.")


if __name__ == "__main__":
    main()
